# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-20 00:17
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodAboutModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='介绍标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '首页关于介绍',
                'verbose_name_plural': '首页关于介绍',
            },
        ),
        migrations.CreateModel(
            name='FoodBlogModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='文章标题')),
                ('content', DjangoUeditor.models.UEditorField(verbose_name='文章内容')),
                ('image', models.ImageField(upload_to='blog/image/%Y/%m', verbose_name='文章图片')),
                ('category', models.CharField(choices=[('Chinese', '中餐'), ('Western_style', '西餐'), ('snack', '小食'), ('event', '美食界的事件')], max_length=50, verbose_name='分类')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
        migrations.CreateModel(
            name='FoodExplainModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='说明标题')),
                ('content', models.TextField(max_length=500, verbose_name='说明内容')),
                ('image', models.ImageField(upload_to='home/explain/%Y/%m/', verbose_name='说明图片')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '服务说明',
                'verbose_name_plural': '服务说明',
            },
        ),
        migrations.CreateModel(
            name='FoodServicesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='服务标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '服务内容',
                'verbose_name_plural': '服务内容',
            },
        ),
        migrations.CreateModel(
            name='FoodShowModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='展示图片标题')),
                ('image', models.ImageField(upload_to='home/introduce/%Y/%m/', verbose_name='展示图片')),
                ('content', models.TextField(verbose_name='展示文字内容')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '首页展示',
                'verbose_name_plural': '首页展示',
            },
        ),
        migrations.CreateModel(
            name='HomePicModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='图片标题')),
                ('image', models.ImageField(max_length=500, upload_to='home/pic/%Y/%m/', verbose_name='主页图片')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '首页图片',
                'verbose_name_plural': '首页图片',
            },
        ),
    ]
