# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-28 02:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_foods', '0006_foodcommentmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodNewModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='新文章介绍标题')),
                ('content', models.TextField(max_length=500, verbose_name='新文章介绍内容')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '新文章介绍内容',
                'verbose_name_plural': '新文章介绍内容',
            },
        ),
    ]
